name: .NET Core Blazor and MAUI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write 
  packages: write

jobs:
  build-and-publish:
    runs-on: macos-15  # Required for net9.0-maccatalyst builds

    env:
      Solution_Name: ZinzotNet.sln
      Maui_Project_Directory: ZinzotNet
      Maui_Project_Path: ZinzotNet/ZinzotNet.csproj
      Test_Project_Path: None  # Update if you add a test project

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.3'

    # Install .NET SDK
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x  # Use .NET 9 for net9.0-maccatalyst

    # Install MAUI workloads
    - name: Install MAUI Workloads
      run: dotnet workload install maui

    # Verify solution file exists
    - name: Verify Solution File
      run: |
        if [ ! -f "$Solution_Name" ]; then
          echo "Solution file $Solution_Name not found!"
          exit 1
        fi

    # Restore dependencies
    - name: Restore Solution
      run: dotnet restore $Solution_Name

    # Build the solution
    - name: Build Solution
      run: dotnet build $Solution_Name --configuration Release --no-restore

    # Execute unit tests (if test project exists)
    - name: Execute Unit Tests
      run: dotnet test $Solution_Name --no-restore --configuration Release
      continue-on-error: true  # Skip if no test project exists

    # Install xmlstarlet for version extraction
    - name: Install xmlstarlet
      run: brew install xmlstarlet

    # Extract ApplicationDisplayVersion from ZinzotNet.csproj
    - name: Extract ApplicationDisplayVersion
      id: get_version
      run: |
        VERSION=$(xmlstarlet sel -t -v "//ApplicationDisplayVersion" $Maui_Project_Path)
        echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
      env:
        Maui_Project_Path: ZinzotNet/ZinzotNet.csproj

    # Publish MAUI project for net9.0-maccatalyst
    - name: Publish MAUI App for macCatalyst
      run: dotnet publish $Maui_Project_Path -f net9.0-maccatalyst -c Release -o ./publish/maccatalyst
      env:
        Maui_Project_Path: ZinzotNet/ZinzotNet.csproj

    - name: List All Files in Working Directory
      run: |
        echo "Recursively listing all files in $(pwd):"
        ls -R

    - name: Package ZinzotNet.app as DMG
      run: |
        mkdir -p ./dmg_temp
        cp -R ./publish/maccatalyst/ZinzotNet.app ./dmg_temp/
        hdiutil create -volname "ZinzotNet" -srcfolder ./dmg_temp -ov -format UDZO ZinzotNet-v${{ env.APP_VERSION }}-maccatalyst.dmg
        mv ZinzotNet-v${{ env.APP_VERSION }}-maccatalyst.dmg ./
        rm -rf ./dmg_temp
  
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.APP_VERSION }}
        name: Release v${{ env.APP_VERSION }}
        draft: false
        prerelease: false
        files: ZinzotNet-v${{ env.APP_VERSION }}-maccatalyst.dmg
        token: ${{ secrets.GITHUB_TOKEN }}